

_FwEnum_CHARACTERPICTURE = {
    SYSTEM = "CHAR_LESTER_DEATHWISH",
    AMMUNATION = "CHAR_AMMUNATION",
    FLEECA = "CHAR_BANK_FLEECA",
    MAZEBANK = "CHAR_BANK_MAZE",
    BOAT = "CHAR_BOATSITE",
    EMERGENCIES = "CHAR_CALL911",
    CALL = "CHAR_CHAT_CALL",
    EPSILON = "CHAR_EPSILON",
    FACEBOOK = "CHAR_FACEBOOK",
    TOURSIT = "CHAR_LS_TOURIST_BOARD",
    LIFEINVADER = "CHAR_LIFEINVADER",
    LSCUSTOM = "CHAR_LS_CUSTOMS",
    WARSTOCK = "CHAR_MILSITE",
    MINOTAUR = "CHAR_MINOTAUR",
    MERRYWEATHER = "CHAR_MP_MERRYWEATHER",
    MUTUAL = "CHAR_MP_MORS_MUTUAL",
    UNICORN = "CHAR_MP_STRIPCLUB_PR",
    PEGASUS = "CHAR_PEGASUS_DELIVERY",
    TAXI = "CHAR_TAXI"
}